version: '3'

services:
  web:
    build: docker/apache
    container_name: ${PROJECT_NAME}_web
    volumes:
      - .:${PROJECT_PATH}
      - ./docker/apache/sites-enabled:/etc/apache2/sites-enabled
    depends_on:
      - db
    ports:
      - 81:80

  db:
    container_name: ${PROJECT_NAME}_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql

  adminer:
    container_name: ${PROJECT_NAME}_adminer
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db_data: