version: '3'
services:
  db_furania:
    container_name: dev-furania-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    networks:
      - symfony
    volumes:
      - ./docker/db/data:/var/lib/mysql

  adminer_furania:
    image: adminer
    restart: always
    networks:
      - symfony
    ports:
      - 8080:8080

  back_furania:
    container_name: dev-furania-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    image: symfony
    depends_on:
      - db_furania
    ports:
      - 81:80
    networks:
      - symfony
    volumes:
      - .:/var/www/

networks:
  symfony: